### ISSUE TITLE
Exit on screen lock

### ISSUE THREAD

**Issue by matematik7** [soumya92/barista#2]
Hi,
when my screen is locked (by xautolock), I get the following error in bar:
`Error: status_command process exited unexpectedly (exit 0)`

This does not happen if I run the command manually, so I have no idea how to check for error messages.

**Comment by soumya92** [comment]
When the screen locks the bar should receive a SIGUSR1 and suspend most processing.

You can try running the command manually, then running "pkill -SIGUSR1 $binary_name" to simulate the screen lock, and see what caused the unexpected exit (although exit 0 is a weird one. Usually the bar exits because of a panic, which is a non-zero exit code...)

**Comment by matematik7** [comment]
Thanks for the suggestions, did not know signals were used to suspend processing.

I've tried manually sending SIGUSR1 and then SIGUSR2 and pausing and resuming works as expected.

Then I added some logging and when locking the screen SIGUSR1 is successful and application paused. Then for some reason i3bar thinks the application exited and shows the error, but the application seems to continue running (paused) and never receives SIGUSR2.

**Comment by soumya92** [comment]
That's really weird. If possible, could you create a gist with the source for your barista instance? I can try to reproduce the issue myself and potentially eliminate something specific to your configuration.

Something else you could try is instead of using xautolock, set a hotkey to toggle the bar's visibility (bindsym $mod+n bar mode toggle) and see if the problem still occurs.

**Comment by matematik7** [comment]
I've tried to do a minimal example, and even the empty bar seems to have the same problem:
```golang
package main

import (
	"log"

	"github.com/soumya92/barista/bar"
)

func main() {

	err := bar.Run()
	if err != nil {
		log.Fatal(err)
	}
}
```

I tried to also toggle the bar's visibility and the problem is the same.

**Comment by soumya92** [comment]
Okay, I definitely don't get that error when using an empty bar, either through a hotkey to hide the bar, or through manually locking the screen, so it looks like something differs between our systems.

Could you post:
- your version of i3
- your version of go
- and the "bar {}" section of your i3config?

For reference, mine are:
- i3 version 4.13 (2016-11-08)
- go version go1.8.1.typealias linux/amd64
- and https://gist.github.com/soumya92/bb53a28c13ed2e6f70bffb3329abb879
(although I doubt the colours make a difference)

I'm curious, in particular, about your i3 config. With signals being involved, I suspect there's something different about your status_command causing more (or less) forking somewhere.

**Comment by matematik7** [comment]
- i3 version: i3 version 4.12 (2016-03-06, branch "4.12") or i3 version 4.13 (2016-11-08) the problem is the same on both versions
- go version: go version go1.8.1 linux/amd64
- i3config (I also tried with absolute path and your gist config (just changed the path))
```
bar {
	position top
	status_command ~/go/bin/i3-barista-bar
}
```

**Comment by soumya92** [comment]
I'm running out of things to try :/

What linux distribution you're using? I have both Ubuntu 14.04 and Debian 9 Testing and I don't see the problem on either.
It could also be the display manager. I'm using LightDM on both, maybe you're using something different? If so, how are you starting i3? (I use the session picker on the LightDM greeter)

Incidentally, do you still see this error if you do "pkill -SIGSTOP i3" and "pkill -SIGCONT i3"? What about "pkill -SIGCHLD i3bar"?

In the meanwhile, I'll work on adding the ability to suppress signal handling to the bar, and hopefully have that checked in today, so that may provide a workaround for you.

**Comment by matematik7** [comment]
I'm running ubuntu 17.04, I'm running i3 directly (started with startx).

It seems i3/i3#1741 is the issue, when I set status_command to "exec ~/go/bin/i3-barista-bar" it works fine.
It also works if I use SuppressSignals(true).

Thank you for your help.
