### ISSUE TITLE
Support for multiple lines in output

### ISSUE THREAD

**Issue by carlpett** [soumya92/barista#227]
Thanks for building barista, I've had a fun time so far!
I wonder if there's a way to support modules with multiple lines of text? I know very little about Pango, which is where I would guess the limitation might lie, if there is one? 
As an example use case, I like having my clock on top of the date, for space saving, but I'd also like to put battery runtime underneath the icon, etc.

**Comment by soumya92** [comment]
Unfortunately it does not seem like this is doable with just pango/i3bar. While you can get smaller superscript and smaller subscript text (using `.Rise` and `.Smaller`), there does not seem to be a way to force the two text spans to start at the same spot, or to add a large negative spaced character between them.

While this would be pretty cool, I think it's infeasible to implement it here since the rendering is constrained by i3bar.

**Comment by carlpett** [comment]
Suspected so, thanks for checking!
