### ISSUE TITLE
sysinfo.procs is not the number of processors

### ISSUE THREAD

**Issue by ericyan** [soumya92/barista#81]
The sysinfo module provides a Procs field for the number of processors/cores. The [sysinfo system call](http://man7.org/linux/man-pages/man2/sysinfo.2.html) actually returns the number of current processes/threads as the value of procs.

I am not sending a PR as I am not sure what would be the best way to resolve this. We can simply update the docs, but that would break the API. Getting the actually number of CPU cores is easy though: `runtime.NumCPU()`.

**Comment by soumya92** [comment]
Heh, that's what I get for writing documentation at night.
I'll update the module documentation to reflect that it's actually the number of processes. It's not really breaking the API, since the value is unchanged. If someone was using that as the number of cores today, they would have seen weird values, so it's better to just document it correctly.
